# Generated by Django 5.2.17 on 2026-09-25 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('skills', models.TextField()),
                ('city', models.CharField(max_length=255)),
                ('salary_min', models.IntegerField(default=0)),
                ('salary_max', models.IntegerField()),
                ('work_mode', models.CharField(choices=[('On-site', 'On-site'), ('Remote', 'Remote')], default='On-site', max_length=255)),
                ('visa_sponsorship', models.BooleanField(default=False)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('note', models.TextField()),
                ('status', models.CharField(choices=[('Applied', 'Applied'), ('Review', 'Review'), ('Interview', 'Interview'), ('Offer', 'Offer'), ('Closed', 'Closed')], default='Applied', max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.job')),
            ],
        ),
    ]
