# Generated by Django 5.2.17 on 2026-09-24 23:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(blank=True, max_length=255)),
                ('skills', models.CharField(blank=True, help_text='Seperate skills w/ comma', max_length=255)),
                ('education', models.TextField(blank=True)),
                ('experience', models.TextField(blank=True)),
                ('links', models.TextField(blank=True, help_text='One link per line')),
                ('role', models.CharField(choices=[('seeker', 'Job seeker'), ('recruiter', 'Recruiter')], default='seeker', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
